# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "imagick"

    filter_sets:
        square_thumbnail_medium:
            filters:
                thumbnail:
                    size: [300, 300]
                    mode: outbound
                    allow_upscale: true

        square_thumbnail_small:
            filters:
                thumbnail:
                    size: [200, 200]
                    mode: outbound
                    allow_upscale: true

        square_thumbnail_vtiny:
            filters:
                thumbnail:
                    size: [150, 100]
                    mode: outbound
                    allow_upscale: true

        # use the default cache configuration
        #cache: ~
