#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_home:
    path:       /
    controller: App\Controller\NavController::homepage

app_categories:
    path:       /categories
    controller: App\Controller\CategoryController::categoriesIndex

app_test:
    path:       /test/demo
